### ISSUE TITLE
Adding list to a list

### ISSUE THREAD

**Issue by vnbaaij** [the-urlist/home#8]
When trying to add a list  to another list, it generates an error in ValidatePage.cs on line 77 (OpenGraph.ParseUrlAsync) and therefore the title and description are not shown with the link in the new list. 
It errors in the backend but I think the problem originates from the routing in the frontend.

**Comment by cecilphillip** [comment]
@vnbaaij this was a trivial repro but here's the thing. Our generated URLs don't have any custom Open Graph metadata or custom titles, so even if we circumvented the exception you would still have to edit the URL description in the list.

The reason you're getting  404s from `ParseUrlAsync` is due to 1) the frontend is a JavaScript application that we're not pre-rendering and 2) the inability of Azure Blob storage to handle SPA routes. 
//cc @burkeholland
